#: kivy 2.0
#: import ScreenManager kivy.uix.screenmanager
#: import CardTransition kivy.uix.screenmanager.CardTransition
#: include ./templates/splash.kv
#: include ./templates/tictactoe.kv
#: include ./templates/menu.kv


ScreenManager:
    id: manager
    transition: CardTransition()
    SplashScreen:
        id: splash
        manager: manager
    TicTacToe:
        id: tictactoe
        manager: manager
    MenuScreen:
        id: menu
        manager: manager
